insert into public.funding_sources (
  id, name, kind, countries, sectors, funding_models, operator_types,
  funding_range, min_usd, max_usd, stage, next_window, description,
  eligibility, application_mode, official_url, application_url,
  verification_status, review_state, last_verified, source_notes
)
values
(
  'source-gef-sgp',
  'GEF Small Grants Programme',
  'Multilateral grant',
  '["Southeast Asia"]'::jsonb,
  '["Clean infrastructure", "Coastal resilience", "Water infrastructure", "Blue economy"]'::jsonb,
  '["Grant"]'::jsonb,
  '["Public-interest entity"]'::jsonb,
  'Usually US$25,000-US$50,000; maximum regular grant US$75,000',
  25000, 75000, 'Pilot', 'Country call schedule varies',
  'UNDP''s GEF Small Grants Programme provides direct support to eligible community-based and non-governmental organizations working in GEF focal areas.',
  'National CBOs and NGOs in participating countries whose proposals align with the country strategy and GEF areas of work.',
  'Open call', 'https://sgp.undp.org/', 'https://sgp.undp.org/about-us-157/how-to-apply.html',
  'Official programme reference', 'published', '2026-08-16',
  'Country calls and national coordinators control the process. Confirm country-level availability before applying.'
),
(
  'source-asean-foundation',
  'ASEAN Foundation Calls for Applications',
  'Foundation grant',
  '["Southeast Asia"]'::jsonb,
  '["Education and skills", "Community health", "Circular manufacturing", "Coastal resilience", "Clean infrastructure"]'::jsonb,
  '["Grant"]'::jsonb,
  '["Company", "Cooperative", "Public-interest entity"]'::jsonb,
  'Call-specific', null, null, 'Pilot', 'Monitor official call page',
  'The ASEAN Foundation publishes periodic calls and programmes across education, community building, environment, media, and business-community engagement.',
  'Varies by programme. Calls may target civil-society organizations, social enterprises, MSMEs, youth, or regional partners.',
  'Open call', 'https://aseanfoundation.org/', 'https://aseanfoundation.org/call-for-applications/',
  'Official call directory; availability varies', 'published', '2026-08-16',
  'The current official call page lists programme-specific deadlines and marks several recent calls closed. Re-check each call before presenting it as active.'
),
(
  'source-global-innovation-fund',
  'Global Innovation Fund',
  'Impact fund',
  '["Southeast Asia"]'::jsonb,
  '["Food production", "Education and skills", "Community health", "Clean infrastructure", "Coastal resilience"]'::jsonb,
  '["Grant", "Debt", "Equity"]'::jsonb,
  '["Company", "Cooperative"]'::jsonb,
  'Stage and instrument dependent', null, null, 'Growth', 'Partner process varies',
  'Global Innovation Fund describes a flexible-capital approach using grants, equity, and debt to scale innovations across Africa and Asia.',
  'High-potential innovations with evidence of impact, a pathway to scale, and fit with climate resilience or inclusive economic opportunity themes.',
  'Partner referral', 'https://www.globalinnovation.fund/', 'https://www.globalinnovation.fund/partnerships',
  'Official programme reference', 'published', '2026-08-16',
  'The programme page does not mean every project can apply directly. Do not represent a match as an invitation to apply.'
),
(
  'source-globalgiving',
  'GlobalGiving Pathway',
  'Philanthropy platform',
  '["Southeast Asia"]'::jsonb,
  '["All sectors"]'::jsonb,
  '["Grant"]'::jsonb,
  '["Public-interest entity"]'::jsonb,
  'Campaign dependent', null, null, 'Pilot', 'Cohort intake varies',
  'GlobalGiving connects vetted nonprofit projects with donors and companies, and provides a pathway to become a fundraising partner.',
  'Nonprofit organizations must complete the pathway and due-diligence process; participation is not automatic after the interest survey.',
  'Partner referral', 'https://www.globalgiving.org/', 'https://www.globalgiving.org/apply/',
  'Official platform reference', 'published', '2026-08-16',
  'The official pages describe cohort-based intake and due diligence. Fees apply to donations; confirm current partner terms.'
)
on conflict (id) do update set
  name = excluded.name,
  kind = excluded.kind,
  countries = excluded.countries,
  sectors = excluded.sectors,
  funding_models = excluded.funding_models,
  operator_types = excluded.operator_types,
  funding_range = excluded.funding_range,
  min_usd = excluded.min_usd,
  max_usd = excluded.max_usd,
  stage = excluded.stage,
  next_window = excluded.next_window,
  description = excluded.description,
  eligibility = excluded.eligibility,
  application_mode = excluded.application_mode,
  official_url = excluded.official_url,
  application_url = excluded.application_url,
  verification_status = excluded.verification_status,
  review_state = excluded.review_state,
  last_verified = excluded.last_verified,
  source_notes = excluded.source_notes,
  updated_at = now();
